name: All Branches CI

on:
  push:
    branches: [ "*", "!main" ]
  pull_request:
    branches: [ "*", "!main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Solo fuera de main
        run: date "+%Y-%m-%d %H:%M:%S.%3N"
  #build:
  #  uses: ./.github/workflows/common.yml
