name: All Branches CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - name: SonarQube
      run: echo "mvn verify"

    - name: Build binary
      run: |
        echo "Hola mundo" > compiled.txt
        ls -la
    
    - name: Upload compiled
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: compiled.txt

  accept:
    name: Acceptance testing
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Download compiled
      uses: actions/download-artifact@v3
      with:
        name: compiled

    - name: Acceptance testing
      run: date "+%Y-%m-%d %H:%M:%S.%3N"

    - name: List
      run: ls -la

    # - name: Build with Maven
    #  run: mvn -B package --file pom.xml
