name: All Branches CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - name: SonarQube
      run: echo "SonarQube"

    - name: Unit testing
      run: echo "Unit testing"

    - name: Integration testing
      run: echo "Integration testing"

    - name: Jacoco
      run: echo "Jacoco"

    - name: Dependency check
      run: echo "testing"

    - name: Build binary
      run: echo "Hola mundo" > compiled.txt

    - name: List
      run: ls -la

  accept:
    name: Acceptance testing
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Acceptance testing
      run: date "+%Y-%m-%d %H:%M:%S.%3N"

    - name: List
      run: ls -la

    # - name: Build with Maven
    #  run: mvn -B package --file pom.xml
