name: All Branches CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SonarQube
      run: echo "SonarQube"

    - name: Unit testing
      run: echo "Unit testing"

    - name: Integration testing
      run: echo "Integration testing"

    - name: Jacoco
      run: echo "Jacoco"

    - name: Dependency check
      run: echo "testing"

  accept:
    runs-on: ubuntu-latest

    - name: Include only main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      run: date "+%Y-%m-%d %H:%M:%S.%3N"
  #build:
  #  uses: ./.github/workflows/common.yml
