name: Main Branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# https://docs.github.com/es/actions/using-workflows/events-that-trigger-workflows#workflow_run
# https://stackoverflow.com/questions/63343937/how-to-use-the-github-actions-workflow-run-event
#  workflow_run:
#    workflows: [All Branches CI]
#    types:
#      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use commoun
      run: ls -la ./.github
      # uses: ./.github/workflows/common.yml

    - name: Acceptance testing
      run: date "+%Y-%m-%d %H:%M:%S.%3N"


# - name: Build with Maven
#  run: mvn -B package --file pom.xml
