name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Acceptance testing
      run: ls
      
	  # - name: Build with Maven
	  #  run: mvn -B package --file pom.xml
