name: Main Branch CI

on:
# https://docs.github.com/es/actions/using-workflows/events-that-trigger-workflows#workflow_run
#  workflow_run:
#    workflows: [All Branches CI]
#    types:
#      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Acceptance testing
      run: echo "testing"

# - name: Build with Maven
#  run: mvn -B package --file pom.xml
