name: Main Branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Acceptance testing
      run: echo "testing"

# - name: Build with Maven
#  run: mvn -B package --file pom.xml
